spring:
  # database access
  datasource:
    url: jdbc:h2:./liquibase;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ''

# in memory
#  datasource:
#    url: jdbc:h2:./liquibase;DB_CLOSE_ON_EXIT=FALSE
#    username: sa
#    password: ''

# local postgresql
#  datasource:
#    url: jdbc:postgresql://localhost:5432/imageviewer
#    username: postgres
#    password: postgres

  liquibase:
    enabled: true
    change-log: 'classpath:db/changelog/db.changelog-master.yaml'
  jpa:
    hibernate:
      ddl-auto: validate

      # if you want to use liquibase
      # ddl-auto: validate

      # if you want to let spring data update the db schema
      # ddl-auto: update

log:
  single-line: false
  skip-classes: >
    FastClassBySpringCGLIB,
    EnhancerBySpringCGLIB,
    java.lang.reflect.Method.invoke,
    jdk.internal.reflect,
    org.apache.catalina,
    org.apache.coyote,
    org.apache.tomcat,
    org.springframework.aop.framework,
    org.springframework.aop.aspectj,
    org.springframework.cglib.proxy.MethodProxy.invoke,
    org.springframework.security.web.FilterChainProxy,
    org.springframework.web.filter.OncePerRequestFilter.doFilter,
    org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke,
    org.springframework.web.method.support.InvocableHandlerMethod,
    org.springframework.web.servlet.mvc.method.annotation,
    org.springframework.web.filter,
    it.vitalegi.metrics.PerformanceAspect.logExecutionTime

metrics:
  skipIfLessThan: 50

viewer:
  output: C:/a/projects/vitalegi/image-viewer/out
  paths:
    - name: test1
      path: C:/a/projects/vitalegi/image-viewer/20221006-20221010_test
